### PR TITLE
included the functionality to load custom fonts (ds-digital)

### PR DESCRIPTION
**Pull request by aadil6971**
it looks like the is no way to load custom fonts with tkinter but you can use the system font so i made a way to load in custom font (ds-digital) in the memory so that our tkinter program can pick it and load it.

### CODE REVIEW

**Comment by PandaSupremacy** [comment]
I am new to tkinter and I don't understand most of the code. Could you explain what the extra lines of code are doing?

**Comment by aadil6971** [comment]
i didnt add much in tkinter 
I added a new file Fonts.py that uses ctypes to get access to windows functionalities
so the custom font that you have in your folder, i load that in and send a message to every running program that a new font is available and as we have already specified the name of that font in our tkinter section the font gets loaded automatically
this way you can add any font that you like , alll you need is a font file thats it.

**Comment by PandaSupremacy** [comment]
that is so informative thank you so much
let me run it

**Comment by PandaSupremacy** [comment]
So, I was not aware that I had to install the fonts separately and that caused all the issues.  Now the code is working fine with that minor change. I appreciate your efforts anyways. Thanks!

**Comment by aadil6971** [comment]
Yes thats the quick fix , you can manually install the font but if you want to automate the process ,  so then when someone else tries to run the program they dont have to install the font manually.

**Comment by PandaSupremacy** [comment]
okay, I am doing this for learning purposes so I will definitely try to understand your code and make amends once I do.

**Pull request closed without merging**
